plugin: aws_ec2

#aws_access_key: AKIAWBJI536EQ75BAO5F
#aws_secret_key: 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

regions:
  - ap-southeast-1

filters:
  "Name=tag-key,Values=host machines"
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
