plugin: aws_ec2

aws_access_key: AKIAX5AGJN36EX55D55P
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
